// 메인 section2 
const m_bestData = {
    bestItem0: [
        {   name: "베이직 메리제인 플랫 1.0 HPWWFC402S",
            img: "./images/goods/women/shoes/flat/item_5_on.jpg",
            oprice: "19900",
            dprice: "14880",
            review: "129",
        },
        {   name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
            img: "./images/goods/men/shoes/slippers/item_4_on.jpg",
            oprice: "19900",
            dprice: "15900",
            review: "6",
        },
        {   name: "[NAVY] 베이직 캔버스 덱 슈즈 HPCR3CA03S",
            img: "./images/goods/men/shoes/sneakers/item_6_on.jpg",
            oprice: "29900",
            dprice: "17900",
            review: "63",
        },
        {   name: "슈펜 X 비슬로우 리커버리 슬라이더 HPCV5B204M",
            img: "./images/goods/men/shoes/slippers/item_6_on.jpg",
            oprice: "19900",
            dprice: "11900",
            review: "32",
        },
    ],
    bestItem1: [
        {   name: "코튼 블렌드 케이블 버킷햇 HPACSD301M",
            img: "./images/goods/women/ac/hats/item_5_on.jpg",
            oprice: "19900",
            dprice: "11900",
            review: "32",
        },
        {   name: "화섬 베이직 버킷햇 2 TPCH79W04",
            img: "./images/goods/women/ac/hats/item_6_on.jpg",
            oprice:"15900",
            dprice:"12900",
            review:"3",
        },
        {   name: "STND 헤링본 버킷햇 HPACHCA55M",
            img: "./images/goods/men/ac/hats/item_7_on.jpg",
            oprice: "29900",
            dprice: "18630",
            review: "19",
        },
        {   name: "STND 버킷햇 HPACHCA56M",
            img: "./images/goods/men/ac/hats/item_9_on.jpg",
            oprice: "29900",
            dprice: "17900",
            review: "19",
        },
    ],
    bestItem2: [
        {   name: "리커버리 소프트 젤리샌들 HPCV1D381Q",
            img: "./images/goods/women/shoes/sandal/item_6_on.jpg",
            oprice:"19900",
            dprice:"17910",
            review:"",
        },
        {   name: "사선 스트랩 쪼리 젤리 샌들 1.0 HPWWND231D",
            img: "./images/goods/women/shoes/sandal/item_8_on.jpg",
            oprice:"19900",
            dprice:"17910",
            review:"",
        },
        {   name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D381M",
            img: "./images/goods/men/shoes/slippers/item_3_on.jpg",
            oprice: "19900",
            dprice: "15900",
            review: "59",
        },
        {   name: "키즈 리커버리 슬리퍼 HPKV5D201U",
            img: "./images/goods/kids/shoes/sandal/item_11_on.jpg",
            oprice: "15900",
            dprice: "9900",
            review: "61",
        },
    ],
}

export default m_bestData;