// new/best 페이지 상품 데이터
const prdData = {
    // 1. new 상품 데이터
    "new": {
        "women": [
            {   name: "케이블 삭스",
                img: "women/new/item_1.jpg",
                oprice: "",
                dprice: "3900",
                review: "42", 
            },
            {   name: "[경량EVA] 더블스트랩 리커버리 슬리퍼",
                img: "women/new/item_2.jpg",
                oprice: "25900",
                dprice: "24900",
                review: "17", 
            },
            {   name: "나일론 스트링 백팩",
                img: "women/new/item_3.jpg",
                oprice: "39900",
                dprice: "30320",
                review: "51", 
            },
            {   name: "[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img: "women/new/item_4.jpg",
                oprice: "25900",
                dprice: "24900",
                review: "53", 
            },
            {   name: "스퀘어 미디엄 숄더백",
                img: "women/new/item_5.jpg",
                oprice: "29900",
                dprice: "27900",
                review: "4", 
            },
            {   name: "미니 스퀘어 크로스백",
                img: "women/new/item_6.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "20", 
            },
            {   name: "스퀘어 미니 토트백",
                img: "women/new/item_7.jpg",
                oprice: "29900",
                dprice: "27900",
                review: "21", 
            },
            {   name: "화섬 포켓 백팩",
                img: "women/new/item_8.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "22", 
            },
            {   name: "청키 트랙솔 메리제인 5.0",
                img: "women/new/item_9.jpg",
                oprice: "49900",
                dprice: "46900",
                review: "23", 
            },
            {   name: "오버솔 와이드 4CM 리프트 스니커즈",
                img: "women/new/item_10.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "24", 
            },
            {   name: "스퀘어 가보시 힐 샌들",
                img: "women/new/item_11.jpg",
                oprice: "",
                dprice: "39900",
                review: "", 
            },
            {   name: "벨트 스트랩 클로그 뮬 3.5",
                img: "women/new/item_12.jpg",
                oprice: "49900",
                dprice: "46900",
                review: "26", 
            },
            {   name: "스퀘어 리본 투웨이 샌들",
                img: "women/new/item_13.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "27", 
            },
            {   name: "[고프코어] 스카치 트랙 스니커즈",
                img: "women/new/item_14.jpg",
                oprice: "49900",
                dprice: "46900",
                review: "28", 
            },
            {   name: "청키 레이스업 패딩 샌들",
                img: "women/new/item_15.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "29", 
            },
            {   name: "슬림 컵솔 스니커즈",
                img: "women/new/item_16.jpg",
                oprice: "39900",
                dprice: "36900",
                review: "7", 
            },
        ],
        "men": [
            {   name: "[경량EVA] 더블스트랩 리커버리 슬리퍼",
                img: "men/new/item_1.jpg",
                oprice: "25900",
                dprice: "24900",
                review: "2", 
            },
            {   name: "나일론 스트링 백팩",
                img: "men/new/item_2.jpg",
                oprice: "39900",
                dprice: "30320",
                review: "3", 
            },
            {   name: "빈티지 레터링 볼캡",
                img: "men/new/item_3.jpg",
                oprice: "25900",
                dprice: "23900",
                review: "4", 
            },
            {   name: "[시누 PICK] 오솔라이트 유니 레더 독일군",
                img: "men/new/item_4.jpg",
                oprice: "59900",
                dprice: "45520",
                review: "5", 
            },
            {   name: "베이직 코트화",
                img: "men/new/item_5.jpg",
                oprice: "59900",
                dprice: "56900",
                review: "6", 
            },
            {   name: "[오솔라이트] 유니레더 NEW ARMY 독일군 스니커즈 4.5cm키높이",
                img: "men/new/item_6.jpg",
                oprice: "59900",
                dprice: "45520",
                review: "7", 
            },
            {   name: "[에어쿠션] 초경량 논슬립 슬립온 워킹화",
                img: "men/new/item_7.jpg",
                oprice: "39900",
                dprice: "37900",
                review: "8", 
            },
            {   name: "소프트 슬림 베이직 스니커즈",
                img: "men/new/item_8.jpg",
                oprice: "59900",
                dprice: "29900",
                review: "9", 
            },
            {   name: "[경량EVA] 아웃도어 투 벨크로 샌들",
                img: "men/new/item_9.jpg",
                oprice: "39900",
                dprice: "29900",
                review: "10", 
            },
            {   name: "오버솔 스니커즈",
                img: "men/new/item_10.jpg",
                oprice: "49900",
                dprice: "46900",
                review: "11", 
            },
            {   name: "크로스 스트랩 슬라이드",
                img: "men/new/item_11.jpg",
                oprice: "",
                dprice: "19900",
                review: "15900", 
            },
            {   name: "[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img: "men/new/item_12.jpg",
                oprice: "25900",
                dprice: "19900",
                review: "12", 
            },
            {   name: "무지 코튼 라운드 버킷햇",
                img: "men/new/item_13.jpg",
                oprice: "29900",
                dprice: "19900",
                review: "32", 
            },
            {   name: "[경량EVA] 어글리 리커버리 쪼리",
                img: "men/new/item_14.jpg",
                oprice: "29900",
                dprice: "14900",
                review: "43", 
            },
            {   name: "[경량EVA] 논슬립 베이직 리커버리 쪼리",
                img: "men/new/item_15.jpg",
                oprice: "",
                dprice: "15900",
                review: "5", 
            },
            {   name: "슈펜 X 비슬로우 리커버리 슬라이더",
                img: "men/new/item_16.jpg",
                oprice: "19900",
                dprice: "9900",
                review: "53", 
            },
        ],
        "kids": [
            {   name: "[FW신상] 키즈 부클자수 피치 볼캡",
                img: "kids/new/item_1.jpg",
                oprice: "19900",
                dprice: "16110",
                review: "2", 
            },
            {   name: "[FW신상] 키즈 베이직 컬러 테슬 로퍼",
                img: "kids/new/item_2.jpg",
                oprice: "29900",
                dprice: "24210",
                review: "3", 
            },
            {   name: "[FW신상] 키즈 글리터 리본 쿠션 플랫",
                img: "kids/new/item_3.jpg",
                oprice: "25900",
                dprice: "21510",
                review: "5", 
            },
            {   name: "[FW신상] 키즈 독일군 스니커즈",
                img: "kids/new/item_4.jpg",
                oprice: "39900",
                dprice: "32310",
                review: "5", 
            },
            {   name: "[FW신상] 키즈 메리제인 샤이닝 플랫 구두",
                img: "kids/new/item_5.jpg",
                oprice: "25900",
                dprice: "21510",
                review: "6", 
            },
            {   name: "[FW신상] 키즈 메리제인 버튼 플랫",
                img: "kids/new/item_6.jpg",
                oprice: "25900",
                dprice: "21510",
                review: "7", 
            },
            {   name: "[FW신상] 플랫폼 스트랩 구두",
                img: "kids/new/item_7.jpg",
                oprice: "39900",
                dprice: "33210",
                review: "8", 
            },
            {   name: "[FW신상] [연주회] 키즈 리본 연주회 구두",
                img: "kids/new/item_8.jpg",
                oprice: "39900",
                dprice: "33210",
                review: "9", 
            },
            {   name: "[FW신상] [연주회] 키즈 주얼 벨벳 플랫구두",
                img: "kids/new/item_9.jpg",
                oprice: "39900",
                dprice: "33210",
                review: "10", 
            },
            {   name: "[테디아일랜드] 키즈 모카신",
                img: "kids/new/item_10.jpg",
                oprice: "39900",
                dprice: "35900",
                review: "11", 
            },
            {   name: "[레인보우] 키즈 그래픽 밸크로 실내화",
                img: "kids/new/item_11.jpg",
                oprice: "12900",
                dprice: "9900",
                review: "12", 
            },
            {   name: "[FW신상] 키즈 컬러블록 캠프캡",
                img: "kids/new/item_12.jpg",
                oprice: "25900",
                dprice: "21510",
                review: "13", 
            },
            {   name: "키즈 컬러 체크 우산",
                img: "kids/new/item_13.jpg",
                oprice: "19900",
                dprice: "15900",
                review: "14", 
            },
            {   name: "키즈 피셔맨 말랑 젤리샌들",
                img: "kids/new/item_14.jpg",
                oprice: "19900",
                dprice: "14900",
                review: "15", 
            },
            {   name: "키즈 경량 리커버리 샌들",
                img: "kids/new/item_15.jpg",
                oprice: "29900",
                dprice: "15210",
                review: "16", 
            },
            {   name: "키즈 첼시 레인부츠",
                img: "kids/new/item_16.jpg",
                oprice: "29900",
                dprice: "17910",
                review: "", 
            },
        ]
    },
    // 2. best 상품 데이터
    "best": {

    }
};

export default prdData;