// 메인 section4
const m_newData = {
    // women data
    newItem0: [
        {   name: "미니 스퀘어 크로스백 HPABGD4T01",
            img: "./images/goods/women/new/item_6.jpg",
            oprice: "39900",
            dprice: "36900",
            review: "58",
        },
        {   name: "슬림 컵솔 스니커즈 HPMR6DA802",
            img: "./images/goods/women/new/item_16.jpg",
            oprice: "35900",
            dprice: "34900",
            review: "31",
        },
        {   name: "스퀘어 리본 투웨이 샌들 HPWWND377Q",
            img: "./images/goods/women/new/item_13.jpg",
            oprice: "37000",
            dprice: "29800",
            review: "62",
        },
        {   name: "청키 트랙솔 메리제인 5.0 HPWWCD4902",
            img: "./images/goods/women/new/item_9.jpg",
            oprice: "49900",
            dprice: "46900",
            review: "17",
        },
    ],
    // men data
    newItem1: [
        {   name: "오솔라이트 유니 레더 독일군 HPMR6DA03M",
            img: "./images/goods/men/new/item_4.jpg",
            oprice: "59900",
            dprice: "56900",
            review: "18",
        },
        {   name: "무지 코튼 라운드 버킷햇 HPACHDA03M",
            img: "./images/goods/men/new/item_13.jpg",
            oprice: "39900",
            dprice: "29900",
            review: "104",
        },
        {   name: "크로스 스트랩 슬라이드 HPCV5D3601",
            img: "./images/goods/men/new/item_11.jpg",
            oprice: "15900",
            dprice: "19900",
            review: "43",
        },
        {   name: "더블스트랩 리커버리 슬리퍼 HPCV4D344M",
            img: "./images/goods/men/new/item_1.jpg",
            oprice: "29900",
            dprice: "25900",
            review: "64",
        },
    ],
    // kids data
    newItem2: [
        {   name: "키즈 독일군 스니커즈 HPKR3DA81U",
            img: "./images/goods/kids/new/item_4.jpg",
            oprice: "35900",
            dprice: "32300",
            review: "15",
        },
        {   name: "키즈 그래픽 밸크로 실내화 HPKRUDA03U",
            img: "./images/goods/kids/new/item_11.jpg",
            oprice: "12900",
            dprice: "9900",
            review: "74",
        },
        {   name: "키즈 글리터 리본 쿠션 플랫 HPKWFDA81G",
            img: "./images/goods/kids/new/item_3.jpg",
            oprice: "23900",
            dprice: "21510",
            review: "42",
        },
        {   name: "플랫폼 스트랩 구두 HPKWCD381G",
            img: "./images/goods/kids/new/item_7.jpg",
            oprice: "36900",
            dprice: "33210",
            review: "81",
        },
    ],
};

export default m_newData;